# Generated by Django 5.0.6 on 2024-11-16 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAPP', '0006_alter_profile_user_remove_donation_donationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='HomeAPP.project'),
        ),
        migrations.AddField(
            model_name='featureproject',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='HomeAPP.project'),
        ),
    ]
