# Generated by Django 5.0.6 on 2024-11-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeAPP', '0010_alter_donation_project_alter_featureproject_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureproject',
            name='project',
        ),
    ]
